### ISSUE TITLE
[Externals] tag: latest pulls the latest revision instead of the latest tag

### ISSUE THREAD

**Issue by Adirelle** [ultijlam/curseforge-packager#5]
"tag: latest" is supposed to pull the latest tag of the main branch of the externals. Actually it simply pulls the latest _revision_ of the branch.

Though I reported this bug I intend to work on it -- and to possibly cache externals to speed up the building process (but that's another step).

**Comment by johnnylam88** [comment]
I see that I misread the pkgmeta specification.  Your interpretation looks to be correct. However, there is definitely something wrong with the first example in the pkgmeta specification where it shows a SVN url for the trunk but also has "tag: latest".  It's unclear to me whether we should assume the standard SVN repository structure and just infer the correct URL, or if we're supposed to ignore the tag setting completely.

**Comment by johnnylam88** [comment]
Regarding caching externals, I think passing "-e" and "-o" to the script will do what you want.  It will avoid deleting the package directory before copying files into place, and it will skip checking out externals.  For example, "sh release.sh -z" will create a full release into the package directory, and subsequent "sh release.sh -eoz" will overwrite-copy files and skip checking out externals again.

**Comment by Adirelle** [comment]
Messing with subversion URL is actually an issue. I don't know how the curse packager does but it allows it. We can only assume the standard SVN structure. However, I'm not sure on the best way to get the latest tag.

**Comment by johnnylam88** [comment]
Something like the following should get the latest tag, though maybe not the latest version tag:

```
svn log url://to/svn/repo/tags
```

However, if "tag: latest" just means the latest tag, then this will work.  Just need to filter through some grep/sed/awk command to get the right information.

I'm going to modify the externals section so that it checks out the external code then does a mini-release of the external code to do repository keyword replacement; otherwise, the external checkout might end up with active @debug@ code.

**Comment by johnnylam88** [comment]
I think I've fixed most of the points brought up in this ticket.  Setting "tag" for both SVN and Git externals should work properly now, and externals are first checked out into another directory, followed by a mini-release of that checkout into the final external directory location.  The mini-release causes repository keywords to be replaced.
